resource-config: set collection-name on annotated field
estuary/ui pull request #397
Opened 2022-12-02 15:21 UTC by mdibaiee

## Changes

- Automatically fill in field marked with `x-collection-name` with last piece of collection name

## Tests

Tested locally

## Issues

#311 

## Content

N/A

## Screenshots

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/2807772/205326131-5872bbb3-ae2c-4856-a3fd-a6ef2f22a0cd.png">

2022-12-02 23:04 UTC, travjenkins requested changes
This creates an infinite loop. Do not merge this. I'll take a look at it.

2022-12-03 01:41 UTC, travjenkins approved these changes
Switched the approach to setting the `default` property in the schema. This allows `ajv` to set the value once it makes it into `jsonForms`.

Please test and make sure this is still working as expected for you.

Also... I am assuming we're taking the approach that only a single field should ever have this annotation.

2022-12-03 01:41 UTC, travjenkins commented on src/components/collection/ResourceConfigForm.tsx
> +    }, [resourceSchema.properties]);
This chunk isn't _too_ heavy but since we don't need to recalculate it often decided to move this into a stand alone memo.

2022-12-03 01:42 UTC, travjenkins commented on src/components/collection/ResourceConfigForm.tsx
> +    }, [collectionName, collectionNameFieldKey, resourceSchema]);
Make a memo of the schema which will either be the normal schema or one with the injected default value.

2022-12-03 01:43 UTC, travjenkins commented on src/index.tsx
> +setAutoFreeze(false);
This allows AJV to more easily manipulate the data being passed to it. Related to this change but one I have been eyeing for a while so made it here.

2022-12-03 01:43 UTC, travjenkins commented on src/services/ajv.ts
> +    ajv.addKeyword('x-collection-name'); // Used to default name in resource configs
We keep all custom annotations in here so we can keep them all documented together.

2022-12-05 15:53 UTC, kiahna-tucker approved these changes

2022-12-05 21:52 UTC, merged