feature: Display derivation status (if any) on collections
estuary/ui pull request #428
Opened 2022-12-20 18:25 UTC by jshearer

## Changes
Only shows status if there are derivations. Otherwise we'd be showing a lot of "no shard status found" dots, which felt wrong.

I do wish this were more clear that this is _derivation_ status, and especially which derivation the status is actually representing, but according to @travjenkins that's a known limitation currently. Maybe we need mocks?

Fixes #420

## Screenshots
![Screen Shot 2022-12-20 at 13 22 47](https://user-images.githubusercontent.com/4368270/208739050-04669647-48e0-4232-8a0c-001ca53c72c7.png)

2022-12-21 16:33 UTC, jshearer commented
Based on convo with @dyaffe and note from @kiahna-tucker, I changed non-capture-collections to present a green dot that says "Capture", and I also enabled the shard failures table on collections like it is on captures and materializations.

![Screen Shot 2022-12-21 at 11 32 00](https://user-images.githubusercontent.com/4368270/208956410-a449e4b7-4d89-43aa-bb59-37d79065743f.png)

2022-12-21 18:03 UTC, jshearer commented
This should be good to be reviewed! :)

2022-12-22 16:49 UTC, travjenkins commented
By defaulting collections to Green and label "Collection" this means that when the services is down we get all green
![image](https://user-images.githubusercontent.com/270078/209180190-7f075bd3-c5e0-465c-af70-ad4bb6b1b615.png)

They should be showing black circles as we do with Captures/Materializations
![image](https://user-images.githubusercontent.com/270078/209180263-1db228e4-15ac-4037-9e16-1d2a9c3a04be.png)

2022-12-22 16:50 UTC, travjenkins commented
I pushed a change to where I think this work would start. Mainly because that was a rare error that would show up on LogRocket sometimes and I wanted to catch it so it stopped showing up in the list of errors :)

2022-12-22 16:51 UTC, travjenkins requested changes
Need default color when service is down

2022-12-23 15:43 UTC, travjenkins commented
Made changes so Collections will show nothing if the service is down/cannot be reached

![image](https://user-images.githubusercontent.com/270078/209362102-3af7da12-8e34-465e-bff7-92138ce676a9.png)

2022-12-23 15:57 UTC, travjenkins approved these changes
lgtm - tested everything before and was fine. I pushed changes to make the status clear when things don't work.

2022-12-23 15:58 UTC, merged